Repository RohitKV1n0d/orange_cat_web, pull requests merged in 2024-05, with the labels that each got.

#152 #146 Price Update & Buy Now Button
  static/css/style.css
  static/img/advantages-about-1.svg
  static/img/advantages-about-2.svg
  static/img/advantages-about-3.svg
  static/img/advantages-about-4.svg
  static/img/cont-icon-2.svg
  static/img/cont-icon-3.svg
  static/scss/_structure.scss
  static/scss/style.css
  templates/arrow.html
  templates/bikes.html
  templates/bow.html
  templates/index.html
Labels: enhancement, PR

#154 Navigation Bar Update
  static/css/style.css
  static/js/scripts.js
  templates/base.html
Labels: enhancement, PR

#153 Checking of Responsiveness
  static/css/style.css
  static/img/follow-img.jpg
  templates/index.html
Labels: enhancement, PR

#156 #151 Backend Development for E-commerce Transition and Stripe Integration
  app.py
  requirements.txt
  static/css/style.css
  static/js/scripts.js
  templates/base.html
Labels: PR

#162 My Orders Page
  static/css/style.css
  static/img/download-icon.png
  templates/orders.html
Labels: enhancement, PR

#161 Profile Page
  static/css/style.css
  static/img/testimonial-sample.jpg
  templates/profile.html
Labels: enhancement, PR

#160 Checkout Page
  static/css/style.css
  static/img/order-confirm-img.jpg
  templates/checkout.html
  templates/index.html
Labels: enhancement, PR

#169 Login page new changes
  static/css/style.css
  templates/base.html
  templates/index.html
  templates/login.html
Labels: enhancement, PR

#174 UI Break on welcome back & Create an account.
  static/css/sb-admin-2.min.css
  templates/login.html
  templates/signup.html
Labels: bug, PR

#175 Feature/167 changes need in orangecat cycles
  static/css/style.css
  static/img/No-data.gif
  static/img/follow-us-image.png
  static/img/icons/twitter-new.png
  templates/arrow.html
  templates/bow.html
  templates/index.html
  templates/orders.html
Labels: enhancement, PR

#179 Refactor order display in orders.html #167
  templates/orders.html
Labels: PR

#180 Fix the Typo - Solved
  static/data/product-data.json
Labels: bug, PR

#186 Placeholder Images replaced in Models Section
  static/css/style.css
  static/img/models/arrow/corinto-arrow.jpg
  static/img/models/bow/corinto-bow.jpg
  templates/arrow.html
  templates/bikes.html
  templates/bow.html
Labels: bug, PR

#189 Sticky Footer
  static/css/style.css
Labels: bug, PR

#187 Landing Page Video Fullscreen on Mobile
  static/css/style.css
Labels: enhancement, PR

#195 #194 Location Correction
  templates/contacts.html
Labels: bug, PR
